configure: Add helper to set location of kernel headers and build files
Signed-off-by: David Ahern <dsahern@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -131,6 +131,28 @@ EOF
     echo "HAVE_LIBBPF_PERF_BUFFER__CONSUME:=y" >>"$CONFIG"
 }
 
+find_kernel_path()
+{
+	: ${KVER:=$(uname -r)}
+
+	# Fedora, Redhat and custom kernels
+	if [ -e /lib/modules/${KVER}/source ]; then
+		echo "KSRC=/lib/modules/${KVER}/source" >> "$CONFIG"
+	elif [ -e /usr/src/linux-headers-${KVER} ]; then
+		echo "KSRC=/usr/src/linux-headers-${KVER}" >> "$CONFIG"
+	else
+		echo "Failed to find kernel source directory" >&2
+		return 1
+	fi
+
+	if [ -e /lib/modules/${KVER}/build ]; then
+		echo "KBLD=/lib/modules/${KVER}/build" >> "$CONFIG"
+	else
+		echo "Failed to find kernel build directory" >&2
+		return 1
+	fi
+}
+
 quiet_config()
 {
     cat <<EOF
@@ -170,10 +192,6 @@ check_toolchain
 echo -n "libbpf support: "
 check_libbpf
 
-if [ -n "$KERNEL_HEADERS" ]; then
-    echo "kernel headers: $KERNEL_HEADERS"
-    echo "CFLAGS += -I$KERNEL_HEADERS" >>$CONFIG
-    echo "BPF_CFLAGS += -I$KERNEL_HEADERS" >>$CONFIG
-fi
+find_kernel_path || exit 1
 
 mv $CONFIG $CONFIG_FINAL
